apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: monitoring

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack-crds
  namespace: monitoring
  version: 69.5.2
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesFile: values.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-options: ServerSideApply=true,Replace=true
  target:
    kind: CustomResourceDefinition