apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mauriquev/homelab
    targetRevision: HEAD
    path: ./infrastructure/base/cert-manager
    helm:
      releaseName: cert-manager
      values: |
        values:
          crds:
            enabled: true
          extraArgs:
            - --dns01-recursive-nameservers-only
            - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
  destination:
    namespace: cert-manager
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true