apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-clusterissuer
spec:
  acme:
    email: user@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-acme-key
    solvers:
    - dns01:
        cloudflare:
          apiKeySecretRef:
            name: cloudflare-token-secret
            key: api-token