apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: monitoring  # Make sure this is the same namespace as your Grafana deployment
spec:
  secretName: grafana-tls  # This matches the secretName in your ingress configuration
  issuerRef:
    name: cert-manager-clusterissuer
    kind: ClusterIssuer
  dnsNames:
  - grafana.maurihomelab.net