apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-prometheus-stack
  - certificate.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,PruneLast=true

patches:
  # CRD patch
  - target:
      kind: CustomResourceDefinition
      name: prometheusagents.monitoring.coreos.com
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
  
  # Add ServerSideApply for all CRDs
  - target:
      kind: CustomResourceDefinition
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
  
  # RBAC resources with conflict issues - using ServerSideApply
  - target:
      kind: ClusterRole
      name: kube-prometheus-stack-admission
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true,Replace=true

  - target:
      kind: ClusterRoleBinding
      name: kube-prometheus-stack-admission
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true,Replace=true

  - target:
      kind: Role
      name: kube-prometheus-stack-admission
      namespace: monitoring
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true,Replace=true

  - target:
      kind: RoleBinding
      name: kube-prometheus-stack-admission
      namespace: monitoring
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true,Replace=true
      
  # Handle the webhook related resources
  - target:
      kind: ValidatingWebhookConfiguration
      name: kube-prometheus-stack-admission
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
      
  # Add a generic patch for the prometheus-operator related resource
  - target:
      kind: Deployment
      name: kube-prometheus-stack-operator
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true