apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-prometheus-stack
  - certificate.yaml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patches:
  - patch: |
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: prometheusagents.monitoring.coreos.com
        annotations:
          argocd.argoproj.io/sync-options: ServerSideApply=true
    target:
      kind: CustomResourceDefinition
      name: prometheusagents.monitoring.coreos.com
      
  - patch: |
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: kube-prometheus-stack-admission
        annotations:
          argocd.argoproj.io/sync-options: ServerSideApply=true
    target:
      kind: ClusterRole
      name: kube-prometheus-stack-admission