# staging/linkding/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkding

resources:
- ../../base/linkding
- cloudflare.yaml
- sealed-cloudflare-secret.yaml
- sealed-linkding-env-secret.yaml

# Add transformers to add sync waves to specific resources
transformers:
- |-
  apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: add-namespace-syncwave
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  fieldSpecs:
  - path: metadata/annotations
    create: true
    kind: Namespace
- |-
  apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: add-configmap-syncwave
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  fieldSpecs:
  - path: metadata/annotations
    create: true
    kind: ConfigMap
- |-
  apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: add-deployment-syncwave
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  fieldSpecs:
  - path: metadata/annotations
    create: true
    kind: Deployment