apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding/
  - cloudflare.yaml
  - sealed-cloudflare-secret.yaml
  - sealed-linkding-env-secret.yaml

  # Use patches to apply sync-wave annotations to specific resources
