---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgB6r92/Hk/Zp+o03ABvaMwVcs5pfkEJlxOIK3HP/+aZzrzVkFq6qsasN9N4W7B014SQ4xNI4t3bBNnHyfQ+lIAUdffgs45VQ5+eQnY8y0Yd9VMYxIuEiCcRP6acjarl8TdM/K/m+QxNYx1zP4c2WVEKFyPeHdvZOdEBqThXlJ7Ub0DPabhU4XoI+g4Zmub2yfs1XU0Xkpa7+azkADWh+/ZNGX620tqPvjpGPL10DexU70ZxwNbPUMAXYFSsCe2Kn+xHvhG5BZ7o7na1g+Eh8O49LIRGhXOQWlprSrH5AO6hEk9jw9wsr9t4Hrat7AJ9ePFXrPnWzmUcN3SNe8HRBsaI0Gtf1vKFR3zx92Ruttd6PPwOLsd/IgxsZVdyb7JcCtaZnpvQHBsfVSP2hMkKDi1Xzi60j4m5yX1v4cF3YR1YBpAc+ox9pOLbCpPbAgAUckjCkhe+ezJd/tOJfby4zvX0UPX5Ggqvm47z2Ejw1dDsjIlR/Y71Pmz0plfROBSxfVJ2I/CpqwDrIJOu/pz9ifoUVNidAmE34euzC6ag5ZwS18Gc3OIGw4MACqhqDpRGhhfD48Bd2QWiE5qjTb4jqQ3RrfC+mXh4V8/B0q/bi6/+MHZCm32kUPmpPWAkPWN81zXbS8tapjT6qoqurTOJt8SVT7NhofQl5gWVEqQeSx2HA7NIw7BVjy1YpiDPOgs+8we4VzdJHwCMsLU+uSSpHNLmdr8XdQtr18P98Ag+a6r10AaH1JP8WOKqSdZKQKSaq2doHCqcsfDysj3C1IDuzlfciI1ZLEktiXLS2zfe+JSvjzYAXM8ev9bQkIUl9L82NCk/bjw0C/HxyFlWrLnx/MMEnLUkGDabJjflSY7oiGB8ri+XJrhuntLix7pz6lAyRcFVz248lezKVFhFngDaqsUK9g==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
