---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: tunnel-credentials
spec:
  encryptedData:
    credentials.json: AgCuJRF6wFsp0yCMP9oeD5sda/aln6vK7RTt/Pd5S6g1XsfCV1Swd/p9TbHWHW9yoYJaCC9R3GtGpnMXuoLb6J6QD1gSGkl7DuwN2ej1GdMBng3QKE1XHpDm3E+e2ySyLKT2cuYiwQTZ8FofgrSSb3AB8sLqid5is6z32R4tlFvWYJun7yMHjAyFO+4DiuI/Dn5jwMZ0kvgJARY9r7onBjrmGpTrKaXwuE+EtnAdHHUeWl9zuHJcd1NIDaDS2QoUydNnxYmFXuiyiK2RrY/4MyzLuMYSk5zkICzs5/RN2H1aVstc4j/Phiul4pycFYj2i9Q0HHJgeDdxL17Zzb2srTbVRj7NF0RkMrZCcP36hHbCbvodlBTE6PrQw5PXe5emqKJI+1fZ7ZTbDP+BFAgUH4wIlq71rtRBHLnaaMCAEeFTCMDv6UHEc0u9f5sbaQS8Gkmea/YpDluzpt0Q3yH8kUD154TvPhNVjXNJiKZ8qJuxHeiIEN4SRjnH7P30b1gt3F6FsyGHgOF3CzsnGNxlJXYVJjifxUoXAIy48bzAOBzokJZZWawg7zofQiFzoiXaOXRNNkhBC5+ku3H9TncWHZ/ukn39vqU/Yd6UPYRqdvzks4q05C1WrueBsML/CU8Jf+A6EH9JKzXWlODp4boObWhulSEc3+qP2QFcKgakOT++QMVKrpLBp9wy7Bvc8RMkUjntO/4BS1fT4kiz5yAaTlBuKyq1XclsY8n4YMEmIYd1HFUN7kFpDC4lAOAQwffT2VGcMBbxWZTOu70qgMRdU0ojef4hBHLgotcjFofEIhdXXJBqGl6yR+E3BJz6bmA4rhx5p/y7xYfku//0EQuECofNbMh7MLhxV68ipG3hWGU6tjO0e7FLWRIh1En6xqzTRmNuK6J/FPWbahW0DcFi2+4ydg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: tunnel-credentials
