---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA/BMf6+gZmFu4bPmAWoJE0+de2eaSz+bB74EbyUGQkZlSLK08ntSGHOrE2gG83TsnIxFOVGDpn0ODJJif6nRQ7VopiGdmKB3JcfgMIvAd5Bq2iF+LiEFbhCMrN6yODg0LC8f+SQvaABpRZJ1gIQSWOCP4ogvLJJj4fDyWXnOLr8/oLPz6Oov9Vcecm40tm+BrNKxxSY+vVAEFdO5W0c3Tha5rO4Pg5zHn/438SS7pQIptq0AZ5WFUD0HgfOgriecJUJt+gT+OG4777hmHrkEvyhQ9lyv+SA8Tb92QVjLWT9B4h16vAB6INopy8BAVZ/s+wW7Vss8eSToPZDZ0HjjYmiuPygrVqqqqGVduOq3Zt2vvvwtKyb+eu1eOTupD8vZDwFYH2i229DV19Lvcpzt8JroicPKF4nQUgMyQE2iyq19tsDD04VH07PhiPe5y4txaAE0fzRNs9zc6oJEYIuLKG+nsggajozxqiwDkXcvLX0PHxgDM5W/S1SVPFxkPF9Y1af1jrjflGha0CLIeznWYlxQhRoKaVwflviEr2hnLY7eG9E2QP2kBLVOr+a9MeIKmFkJrby2t5nuCbcNoqUJBEHji90RJBRkOV08XqN8yE5GvEUoVLAaHswdiIFS3sOUaYBHWeuK1SMR89p4fWktC+S7i37etE1vcSGNBHTzg6/FPqtxRD8vIq0GOHpqimkZgSGwKYbJy14TCg9AB6RjKLk3m4uZjFKIWPK8M6njYrsF7H5Xiys0QIkUQB8euJJIrSmqPY1G/tYyZprK3HSL3XPmtlw5xSh64meZK2DPJGBHyN5VSJySnvp/xXGdzDmoUitwpDq6+8ZRzvUkEc24hjVXuGNUf5qHHiCTdL1VJi8JDxJkO3ey38z91dadueYhk/WgIInH9iEBereEF2eMdbug==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
