apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-staging
  namespace: argocd
spec:
  project: default
  # Source of the application manifests
  source:
    repoURL: https://github.com/mauriquev/homelab
    targetRevision: HEAD
    path: cluster/staging
   
  # Destination namespace to deploy the application  
  destination:
    namespace: argocd
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
