apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/mauriquev/homelab
      revision: HEAD
      directories:
      - path: infrastructure/staging/*
  template:
    metadata:
      name: '{{index .path.segments 2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mauriquev/homelab
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 2}}'
      # Ignore Certificate status changes from cert-manager
      ignoreDifferences:
      - group: cert-manager.io
        kind: Certificate
        jsonPointers:
        - /status
       # Ignore SealedSecret status changes from sealed-secrets controller
      - group: bitnami.com
        kind: SealedSecret
        jsonPointers:
        - /status