apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # This helps control the order of synchronization
spec:
  destination:
    namespace: monitoring 
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      valueFiles:
        - ./values.yaml 
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
