apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring 
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.0.0
    helm:
      values: |
        grafana:
          adminPassword: mauri
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts: 
              - grafana.maurihomelab.net
            tls:
              - secretName: grafana-tls-secret
                hosts:
                  - grafana.maurihomelab.net
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - PrunePropagationPolicy=foreground
    #   - PruneLast=true
