apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring 
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 69.0.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $values/monitoring/base/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/mauriquev/homelab  # your repository
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    #   - PrunePropagationPolicy=foreground
    #   - PruneLast=true
