apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- namespace.yaml

# Using remote bases to fetch the CRDs first
bases:
- https://github.com/prometheus-community/helm-charts//charts/kube-prometheus-stack/crds?ref=kube-prometheus-stack-69.5.2

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  namespace: monitoring
  version: 69.5.2
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: false  # Keep this false to avoid conflicts
  valuesFile: values.yaml