apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  namespace: monitoring
  version: 69.5.2
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesFile: values.yaml


patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: prometheuses.monitoring.coreos.com
  patch: |-
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "Replace=true"