apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- namespace.yaml

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  namespace: monitoring
  version: 69.5.2
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true  # Make sure this is set to true
  valuesFile: values.yaml

# Add global annotations to all resources
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true