grafana:
  adminPassword: mauri
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts: 
      - grafana.maurihomelab.net
    tls:
      - secretName: grafana-tls-secret
        hosts:
          - grafana.maurihomelab.net