grafana:
  adminPassword: mauri
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts: 
      - grafana.maurihomelab.net
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.maurihomelab.net
crds:
  create: true
  keep: true

prometheusOperator:
  admissionWebhooks:
    failurePolicy: Ignore
    timeoutSeconds: 30
  manageCRDs: true
  createCustomResource: true