apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./cert-manager          # Staging-specific cert-manager resources
- ../base/sealed-secrets  # Directly use the base sealed-secrets