apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  
namespace: monitoring

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack-crds
  namespace: monitoring
  version: 69.5.2
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true
  valuesInline:
    fullnameOverride: "kube-prometheus-stack-crds"
    # Disable all components since we only want the CRDs
    defaultRules:
      create: false
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    kubeApiServer:
      enabled: false
    kubelet:
      enabled: false
    kubeControllerManager:
      enabled: false
    coreDns:
      enabled: false
    kubeDns:
      enabled: false
    kubeEtcd:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    prometheusOperator:
      enabled: false
    prometheus:
      enabled: false

patches:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        argocd.argoproj.io/sync-options: ServerSideApply=true,Replace=true
  target:
    kind: CustomResourceDefinition