apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "68.*"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create #create crds, then it will upgrade them by createreplace 
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: passw0rd #initial setup password change after pod is up
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts: 
          - grafana.maurihomelab.net
        tls:
         - secretName: grafana-tls-secret
           hosts:
            - grafana.maurihomelab.net