apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager  # Reference base configuration
  - clusterissuer.yaml
  - certificate.yaml
  - cm-ca-secret.yaml