apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base/cert-manager
  - clusterissuer.yaml
  - sealed-cm-ca-secret.yaml

# Add annotations to all resources in this kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

